apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: echo
      taskRef:
        name: echo-hello-world
      resources:
        inputs:
          - name: workspace
            resource: source
    - name: echo2
      taskRef:
        name: echo-hello-world2
      resources:
        inputs:
          - name: workspace
            resource: source
