apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  inputs:
    resources:
      - name: workspace
        type: git
        targetPath: test-projects/tekton-tester-ts
  steps:
    - name: echo
      image: circleci/node:10.17
      command:
        - ls
      args:
        - "-la"
      workingDir: "/workspace/"
    - name: whoami
      image: circleci/node:10.17
      command:
        - ls
      args:
        - "-la"
      workingDir: "/workspace/workspace"
    - name: cp
      image: circleci/node:10.17
      command:
        - cp
      args:
        - "-r"
        - "./"
        - "/workspace/output"
      workingDir: "/workspace/workspace"
