apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world2
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: list
      image: circleci/node:10.17
      command:
        - ls
      args:
        - "-la"
      workingDir: "/workspace/workspace/test-projects/tekton-tester-ts"
    - name: echo
      image: circleci/node:10.17
      command:
        - yarn
      args:
        - "install"
      workingDir: "/workspace/workspace/test-projects/tekton-tester-ts"
    - name: test
      image: circleci/node:10.17
      command:
        - yarn
      args:
        - "test"
      env:
        - name: CI
          value: "true"
      workingDir: "/workspace/workspace/test-projects/tekton-tester-ts"
