apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world2
spec:
  steps:
    - name: echo
      image: node:10.17
      command:
        - echo
      args:
        - "hello world"
