apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: npm-build
spec:
  steps:
    - name: echo
      image: node:10
      command:
        - echo
      args:
        - "npm build and install"
    - name: npm-install
      image: node:10
      command:
        - npm
      args:
        - install
    - name: npm-build
      image: node:10
      command:
        - npm
      args:
        - run
        - build
