---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: yarn-install
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: yarn-install
      image: node:10.17
      command:
        - yarn
      args:
        - install
  outputs:
    resources:
      - name: workspace
        type: git
