---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: yarn-build
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  steps:
    - name: yarn-build
      image: node:10.17
      user
      command:
        - yarn
      args:
        - build
  outputs:
    resources:
      - name: workspace
        type: git

