apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: yarn-test
spec:
  steps:
    - name: echo
      image: node:10
      command:
        - echo
      args:
        - "yarn test"
    - name: yarn-install
      image: node:10
      command:
        - yarn
      args:
        - install
    - name: yarn-test
      image: node:10
      command:
        - yarn
      args:
        - test
