apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-git
spec:
  type: git
  params:
    - name: url
      value: "https://github.com/agiledigital/tekton-test.git"
    - name: revision
      value: master
    - name: submodules
      value: "false"
